#!/usr/bin/ruby
# coding: utf-8

require './config'
require 'cgi'
require 'json'
require 'time'

cgi = CGI.new("html4")

mode = CGI::unescape(cgi['mode'])
ku = CGI::unescape(cgi['ku'])
team = CGI::unescape(cgi['team'])
teamid = CGI::unescape(cgi['teamid'])

# mode = "input"
# ku = "ktab1"
# team = "姶良"

# mode = "get_all_data"
# ku = "ktab1"

# mode = "get_team_result"
# teamid = "ttab1"

# ==================================================
class EkidenTime
  attr_reader :ku, :team, :time
  def initialize(ku, team, time)
    @ku = ku
    @team = team
    @time = time
  end
end

# ==================================================
id2team = Hash::new()
id2team["ttab1"] = "姶良"
id2team["ttab2"] = "鹿児島"
id2team["ttab3"] = "日置"
id2team["ttab4"] = "川薩"
id2team["ttab5"] = "肝属"
id2team["ttab6"] = "川辺"
id2team["ttab7"] = "出水"
id2team["ttab8"] = "曽於"
id2team["ttab9"] = "指宿"
id2team["ttab10"] = "大島"
id2team["ttab11"] = "伊佐"
id2team["ttab12"] = "熊毛"


team_list = [
  "姶良",
  "鹿児島",
  "日置",
  "川薩",
  "肝属",
  "川辺",
  "出水",
  "曽於",
  "指宿",
  "大島",
  "伊佐",
  "熊毛"
]


# --------------------------------------------------
table_header = <<TABLEHEADER
<table class="table table-striped table-bordered">
TABLEHEADER

table_footer = <<TABLEFOOTER
</table>
TABLEFOOTER


# ------------------------------   
def sec_print(sec)
  if sec < 60
    sec_str = "#{sec.to_i}秒"
  elsif sec < 60*60
    min = (sec / 60).floor
    sec = (sec % 60).to_i
    sec_str = "#{min}分#{sec}秒"
  elsif sec < 60*60*24
    hour = (sec / (60*60)).floor
    min = ((sec % (60*60)) / 60).floor
    sec = ((sec % (60*60)) % 60).to_i
    sec_str = "#{hour}時間#{min}分#{sec}秒"
  end
  return sec_str
end

# ------------------------------
def table_content_ku(index, team, time, aira_time)
  diff = sec_print(time - aira_time)
    content = <<CONTENT
<tr>
  <td>#{index}</td>
  <td>#{team}</td>
  <td>#{diff}</td>
  <td>#{time.to_s.gsub(/ \+0900$/,"")}</td>
</tr>
CONTENT
    return content
end

# ------------------------------   
def table_content_team(team, time, diff)
    content = <<CONTENT
<tr>
  <td>#{team}</td>
  <td>#{time.to_s.gsub(/ \+0900$/,"")}</td>
  <td>#{diff}</td>
</tr>
CONTENT
    return content
end

# --------------------------------------------------
if ku=~/ktab([0-9]+)/
  ku = "#{$1}区"
end

data = {}

case mode
when "allreset"
  File.open($data_file,"a+"){|wfp|
    wfp.puts "___reset___"
  }
  data = {
    "body" => "削除完了"
  }


when "start"
  current_time = Time.now.localtime("+09:00").to_s
  ku = "スタート"

  File.open($data_file,"a+"){|wfp|
    wfp.puts "___reset___"
    team_list.each{|team|
      data_set = [ku,team,current_time].join("\t")
      wfp.puts data_set
    }
  }

  data = {
    "body" => "start!"
  }


when "input"
  data_set = [ku,team,Time.now.localtime("+09:00").to_s].join("\t")

  File.open($data_file,"a+"){|wfp|
    wfp.puts data_set
  }

  data = {
    "body" => "input: #{data_set}"
  }

when "get_all_data"

  data_list = []    
  aira_time = nil
  File.open($data_file,"r:UTF-8"){|fp|
    fp.each_line{|line|
      if line =~ /___reset___/
        data_list.clear
        next
      end
      elems = line.chomp.split("\t")
      r_ku = elems[0]
      r_team = elems[1]
      r_time = Time.parse(elems[2]).localtime("+09:00")
      if ku == r_ku
        data_list.push(EkidenTime.new(r_ku, r_team, r_time))
        if r_team == "姶良"
          aira_time = r_time
        end
      end
    }
  }

  buffer = ""
  index = 1
  buffer << table_header

  buffer << <<CONTENT
<tr>
  <td><順位></td>
  <td><チーム></td>
  <td><タイム差></td>
  <td><通過時刻></td>
</tr>
CONTENT

  data_list.sort{|a,b|
    a.time <=> b.time
  }.each{|score|
    buffer << table_content_ku(index, score.team, score.time, aira_time)
    index += 1
  }

  buffer << table_footer

  data = {
    "body" => buffer
  }

when "get_team_result"

  ku_time = Hash::new()
  File.open($data_file,"r:UTF-8"){|fp|
    fp.each_line{|line|
      if line =~ /___reset___/
        ku_time.clear
        next
      end
      elems = line.chomp.split("\t")
      r_ku = elems[0]
      r_team = elems[1]
      r_time = Time.parse(elems[2]).localtime("+09:00")
      
      if id2team[teamid] == r_team
        ku_time[r_ku] = r_time
      end
    }
  }

  buffer = ""
  prev = nil
  buffer << table_header
  ku_time.keys.sort{|a,b|
    ku_time[a] <=> ku_time[b]
  }.each{|ku|
    if prev == nil
      diff = "-"
    else
      diff_sec = ku_time[ku] - prev
      diff = sec_print(diff_sec)
    end
    prev = ku_time[ku]
    buffer << table_content_team(ku, ku_time[ku], diff)
  }
  buffer << table_footer


  data = {
    "body" => buffer
  }
end



buffer = JSON.generate(data)
cgi.out({"Access-Control-Allow-Origin" => "*",
          "Content-Type" => "text/plain; charset=UTF-8"}){buffer}
